database:
    driverClass: oracle.jdbc.driver.OracleDriver
    
    user: SITIIMPO
    
    password: sitiimpo_pwd
    
    url: jdbc:oracle:thin:@192.168.19.16:1521:devs4f
    
    maxWaitForConnection: 1s
    
    validationQuery: " /* Myservice Health Check */ SELECT 1 from dual"
    
    validationQueryTimeout: 3s
    
    initialSize: 1
    
    minSize: 1
    
    maxSize: 8
    
    checkConnectionWhileIdle: false
    
    evictionInterval: 10s
    
    minIdleTime: 30s